export const agentRegistryAbi = [
  {
    inputs: [{ name: "agent", type: "address" }, { name: "metadataURI", type: "string" }],
    name: "registerAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "agent", type: "address" }],
    name: "deactivateAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "agent", type: "address" }],
    name: "suspendAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "agent", type: "address" }],
    name: "reactivateAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "agent", type: "address" }, { name: "metadataURI", type: "string" }],
    name: "updateMetadata",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "addr", type: "address" }],
    name: "isAgentOwner",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "owner", type: "address" }, { name: "agent", type: "address" }],
    name: "isActiveAgent",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "agent", type: "address" }],
    name: "getAgent",
    outputs: [
      { name: "owner", type: "address" },
      { name: "status", type: "uint8" },
      { name: "registeredAt", type: "uint256" },
      { name: "metadataURI", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "owner", type: "address" }],
    name: "getAgentsByOwner",
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalActiveAgents",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "agent", type: "address" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "metadataURI", type: "string" },
    ],
    name: "AgentRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "agent", type: "address" },
      { indexed: true, name: "owner", type: "address" },
    ],
    name: "AgentDeactivated",
    type: "event",
  },
  // Errors
  { inputs: [], name: "ZeroAddress", type: "error" },
  { inputs: [], name: "AgentAlreadyRegistered", type: "error" },
  { inputs: [], name: "AgentNotFound", type: "error" },
  { inputs: [], name: "NotAgentOwner", type: "error" },
  { inputs: [], name: "AgentNotActive", type: "error" },
] as const;
