export const subjectStakeAbi = [
  {
    type: "function",
    name: "stake",
    stateMutability: "nonpayable",
    inputs: [
      { name: "kind", type: "string" },
      { name: "canonical", type: "string" },
      { name: "side", type: "uint8" },
      { name: "amount", type: "uint256" },
      { name: "reason", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "stakeClaim",
    stateMutability: "nonpayable",
    inputs: [
      { name: "parentKind", type: "string" },
      { name: "parentCanonical", type: "string" },
      { name: "statement", type: "string" },
      { name: "side", type: "uint8" },
      { name: "amount", type: "uint256" },
      { name: "reason", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "requestUnbond",
    stateMutability: "nonpayable",
    inputs: [
      { name: "subjectId", type: "bytes32" },
      { name: "side", type: "uint8" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "subjectId", type: "bytes32" },
      { name: "index", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "subjectIdOf",
    stateMutability: "pure",
    inputs: [
      { name: "kind", type: "string" },
      { name: "canonical", type: "string" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "subjects",
    stateMutability: "view",
    inputs: [{ name: "subjectId", type: "bytes32" }],
    outputs: [
      { name: "kind", type: "string" },
      { name: "canonical", type: "string" },
      { name: "exists", type: "bool" },
      { name: "supportTotal", type: "uint256" },
      { name: "challengeTotal", type: "uint256" },
      { name: "stakerCount", type: "uint256" },
      { name: "supportStakers", type: "uint256" },
      { name: "challengeStakers", type: "uint256" },
      { name: "parentId", type: "bytes32" },
      { name: "statement", type: "string" },
    ],
  },
  {
    type: "function",
    name: "positions",
    stateMutability: "view",
    inputs: [
      { name: "subjectId", type: "bytes32" },
      { name: "staker", type: "address" },
    ],
    outputs: [
      { name: "support", type: "uint256" },
      { name: "challenge", type: "uint256" },
      { name: "supportReason", type: "string" },
      { name: "challengeReason", type: "string" },
    ],
  },
  {
    type: "function",
    name: "pendingUnbondCount",
    stateMutability: "view",
    inputs: [
      { name: "subjectId", type: "bytes32" },
      { name: "staker", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getUnbond",
    stateMutability: "view",
    inputs: [
      { name: "subjectId", type: "bytes32" },
      { name: "staker", type: "address" },
      { name: "index", type: "uint256" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "amount", type: "uint256" },
          { name: "side", type: "uint8" },
          { name: "availableAt", type: "uint256" },
          { name: "claimed", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "childClaimCount",
    stateMutability: "view",
    inputs: [{ name: "parentId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "childClaimAt",
    stateMutability: "view",
    inputs: [
      { name: "parentId", type: "bytes32" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "listedStakerCount",
    stateMutability: "view",
    inputs: [{ name: "subjectId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "listedStakerAt",
    stateMutability: "view",
    inputs: [
      { name: "subjectId", type: "bytes32" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "MIN_STAKE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
