export const trustGateAbi = [
  // Depositor functions
  {
    inputs: [{ name: "amount", type: "uint256" }],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "amount", type: "uint256" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "agent", type: "address" }, { name: "amount", type: "uint256" }],
    name: "setAllowance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // Agent functions
  {
    inputs: [{ name: "depositor", type: "address" }, { name: "amount", type: "uint256" }],
    name: "claim",
    outputs: [{ name: "claimId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "claimId", type: "uint256" }],
    name: "releaseClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "claimId", type: "uint256" }],
    name: "approveClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "claimId", type: "uint256" }],
    name: "cancelClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // View functions
  {
    inputs: [{ name: "depositor", type: "address" }],
    name: "deposits",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "depositor", type: "address" }, { name: "agent", type: "address" }],
    name: "allowances",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "claimId", type: "uint256" }],
    name: "getClaim",
    outputs: [
      { name: "depositor", type: "address" },
      { name: "agent", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "tier", type: "uint8" },
      { name: "status", type: "uint8" },
      { name: "releaseTime", type: "uint256" },
      { name: "createdAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "depositor", type: "address" }, { name: "agent", type: "address" }],
    name: "getClaimableAmount",
    outputs: [{ name: "claimable", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "claimCounter",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdc",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DELAY_PERIOD",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "depositor", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "Deposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "depositor", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "Withdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "depositor", type: "address" },
      { indexed: true, name: "agent", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "AllowanceSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "claimId", type: "uint256" },
      { indexed: true, name: "depositor", type: "address" },
      { indexed: true, name: "agent", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "tier", type: "uint8" },
    ],
    name: "ClaimCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "claimId", type: "uint256" }],
    name: "ClaimReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "claimId", type: "uint256" }],
    name: "ClaimApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "claimId", type: "uint256" }],
    name: "ClaimCancelled",
    type: "event",
  },
  // Errors
  { inputs: [], name: "ZeroAddress", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  { inputs: [], name: "InsufficientDeposit", type: "error" },
  { inputs: [], name: "InsufficientAllowance", type: "error" },
  { inputs: [], name: "AgentNotActive", type: "error" },
  { inputs: [], name: "AgentNotScored", type: "error" },
  { inputs: [], name: "AgentScoreExpired", type: "error" },
  { inputs: [], name: "ClaimNotPending", type: "error" },
  { inputs: [], name: "TimeLockNotExpired", type: "error" },
  { inputs: [], name: "NotClaimDepositor", type: "error" },
  { inputs: [], name: "NotAuthorizedCanceller", type: "error" },
  { inputs: [], name: "EscrowRequiresApproval", type: "error" },
] as const;
